version: '3.8'

services:
  # --- MySQL Database ---
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: patient
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Apache Kafka (KRaft Mode) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_KEY_FORMATED: '1'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - internal

  # --- Patient Service ---
  patient-service:
    image: patient-service:latest
    container_name: patient
    ports:
      - "4000:4000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      GRPC_SERVER_PORT: 9010
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/patient?createDatabaseIfNotExist=true
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - internal

  # --- Billing Service ---
  billing-service:
    image: billing-service:latest
    container_name: billing
    environment:
      SERVER_PORT: 4009
      GRPC_SERVER_PORT: 9010
    networks:
      - internal

  # --- Analytic Service ---
  analytic-service:
    image: anayltic-service:latest
    container_name: analytic
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - internal

    # --- api gateway ---
  api-gateay:
    image: api-gateway:latest
    container_name: gateway
    ports:
      - "9090:8080"
    environment:
      SERVER_PORT: 8080
    depends_on:
      - billing-service
    networks:
      - internal

# --- Shared Docker Network ---
networks:
  internal:
    driver: bridge