server:
  port: 8080

auth:
  service:
    url: http://auth:7070

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth:7070
          predicates:
            - Path=/api/auth/**, /api/v1/**

        - id: patient-service
          uri: http://patient:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - JwtValidation

        - id: billing-service
          uri: http://billing:4009
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=2
